# Generated by Django 5.2.6 on 2025-09-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=15)),
                ('slug', models.CharField(max_length=150)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
            ],
        ),
    ]
