# Generated by Django 5.2.6 on 2025-09-11 06:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='geeks_field',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300000),
        ),
    ]
