# Generated by Django 5.2.6 on 2025-09-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post_geeks_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='geeks_field',
            new_name='newcontent',
        ),
    ]
