# Generated by Django 5.2.6 on 2025-09-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_rename_geeks_field_post_newcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
